### ISSUE TITLE
tables?

### ISSUE THREAD

**Issue by jVaraldi** [chaberko-lbbe/clec-poolseq#1]
Dear Chloé,
Thank you for sharing your git with me!
Could you please add the datasets to reproduce the analysis??
MERCI !
et a demain

**Comment by chaberko-lbbe** [comment]
Dear Julien,

Thank you for interest ;-)

Link to the repository with the table has been added (doi.org/10.5061/dryad.9cnp5hqp6).

--
Chloé Haberkorn
PhD Student

Laboratoire de Biométrie et Biologie Evolutive
UMR CNRS 5558
Université Claude Bernard - Lyon 1
43 boulevard du 11 novembre 1918, Bâtiment Mendel, 1er étage
69622 Villeurbanne Cedex

tel: +33 (0)6 79 54 33 01
________________________________
De : jVaraldi <notifications@github.com>
Envoyé : lundi 1 mars 2021 17:55
À : chaberko-lbbe/PhD-bedbugs
Cc : Subscribed
Objet : [chaberko-lbbe/PhD-bedbugs] tables? (#1)


Dear Chloé,
Thank you for sharing your git with me!
Could you please add the datasets to reproduce the analysis??
MERCI !
et a demain

-
